// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// 2016-12-28
// 22:49:21
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#include   "App.h"
#include "freemaster_tsa.h"

//--------------------------------------------------------------------------------------------------------------

#if APP_PLATF == ANSIN

extern T_LDC1101_registers LDC1101_regs[LDC1101_DEVS_CNT];
extern uint32_t  g_PIT_counter;
extern uint32_t  g_spi_wr_err;
extern uint32_t  g_spi_rd_err;



FMSTR_TSA_TABLE_BEGIN(tbl_vars)

FMSTR_TSA_RW_VAR(OSStatTaskCPUUsage             , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(OSStatTaskCPUUsageMax          , FMSTR_TSA_UINT16)


FMSTR_TSA_RW_VAR(g_PIT_counter                  , FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(cdata.rcount                   , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(cdata.offset                   , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(cdata.ax                       , FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(cdata.ox                       , FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(cdata.ay                       , FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(cdata.oy                       , FMSTR_TSA_UINT32)

FMSTR_TSA_RW_VAR(lhr_data[0]                    , FMSTR_TSA_SINT32)
#ifndef COIL_RESEARCH
FMSTR_TSA_RW_VAR(lhr_data[1]                    , FMSTR_TSA_SINT32)
FMSTR_TSA_RW_VAR(lhr_data[2]                    , FMSTR_TSA_SINT32)
FMSTR_TSA_RW_VAR(lhr_data[3]                    , FMSTR_TSA_SINT32)
#endif
FMSTR_TSA_RW_VAR(lhr_data_sum                   , FMSTR_TSA_SINT32)
FMSTR_TSA_RW_VAR(xsig                           , FMSTR_TSA_FLOAT )
FMSTR_TSA_RW_VAR(ysig                           , FMSTR_TSA_FLOAT )
FMSTR_TSA_RW_VAR(g_spi_wr_err                   , FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(g_spi_rd_err                   , FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(g_fmstr_rate_src               , FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(g_fmstr_smpls_period           , FMSTR_TSA_FLOAT )
FMSTR_TSA_RW_VAR(g_angle_smpl_period            , FMSTR_TSA_FLOAT )
FMSTR_TSA_RW_VAR(g_RPS                          , FMSTR_TSA_FLOAT )

FMSTR_TSA_RW_VAR(g_angle                        , FMSTR_TSA_FLOAT )

FMSTR_TSA_RW_VAR(LDC1101_regs[0].RP_SET         , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[0].TC1            , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[0].TC2            , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[0].DIG_CONFIG     , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[0].ALT_CONFIG     , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[0].RP_THRESH_H_LSB, FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[0].RP_THRESH_H_MSB, FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[0].RP_THRESH_L_LSB, FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[0].RP_THRESH_L_MSB, FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[0].INTB_MODE      , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[0].START_CONFIG   , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[0].D_CONF         , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[0].L_THRESH_HI_LSB, FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[0].L_THRESH_HI_MSB, FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[0].L_THRESH_LO_LSB, FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[0].L_THRESH_LO_MSB, FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[0].STATUS         , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[0].RP_DATA_LSB    , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[0].RP_DATA_MSB    , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[0].L_DATA_LSB     , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[0].L_DATA_MSB     , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[0].LHR_RCOUNT_LSB , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[0].LHR_RCOUNT_MSB , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[0].LHR_OFFSET_LSB , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[0].LHR_OFFSET_MSB , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[0].LHR_CONFIG     , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[0].LHR_DATA_LSB   , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[0].LHR_DATA_MID   , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[0].LHR_DATA_MSB   , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[0].LHR_STATUS     , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[0].RID            , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[0].CHIP_ID        , FMSTR_TSA_UINT16)

#ifndef COIL_RESEARCH
FMSTR_TSA_RW_VAR(LDC1101_regs[1].RP_SET         , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[1].TC1            , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[1].TC2            , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[1].DIG_CONFIG     , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[1].ALT_CONFIG     , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[1].RP_THRESH_H_LSB, FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[1].RP_THRESH_H_MSB, FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[1].RP_THRESH_L_LSB, FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[1].RP_THRESH_L_MSB, FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[1].INTB_MODE      , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[1].START_CONFIG   , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[1].D_CONF         , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[1].L_THRESH_HI_LSB, FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[1].L_THRESH_HI_MSB, FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[1].L_THRESH_LO_LSB, FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[1].L_THRESH_LO_MSB, FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[1].STATUS         , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[1].RP_DATA_LSB    , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[1].RP_DATA_MSB    , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[1].L_DATA_LSB     , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[1].L_DATA_MSB     , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[1].LHR_RCOUNT_LSB , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[1].LHR_RCOUNT_MSB , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[1].LHR_OFFSET_LSB , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[1].LHR_OFFSET_MSB , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[1].LHR_CONFIG     , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[1].LHR_DATA_LSB   , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[1].LHR_DATA_MID   , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[1].LHR_DATA_MSB   , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[1].LHR_STATUS     , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[1].RID            , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[1].CHIP_ID        , FMSTR_TSA_UINT16)

FMSTR_TSA_RW_VAR(LDC1101_regs[2].RP_SET         , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[2].TC1            , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[2].TC2            , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[2].DIG_CONFIG     , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[2].ALT_CONFIG     , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[2].RP_THRESH_H_LSB, FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[2].RP_THRESH_H_MSB, FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[2].RP_THRESH_L_LSB, FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[2].RP_THRESH_L_MSB, FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[2].INTB_MODE      , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[2].START_CONFIG   , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[2].D_CONF         , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[2].L_THRESH_HI_LSB, FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[2].L_THRESH_HI_MSB, FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[2].L_THRESH_LO_LSB, FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[2].L_THRESH_LO_MSB, FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[2].STATUS         , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[2].RP_DATA_LSB    , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[2].RP_DATA_MSB    , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[2].L_DATA_LSB     , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[2].L_DATA_MSB     , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[2].LHR_RCOUNT_LSB , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[2].LHR_RCOUNT_MSB , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[2].LHR_OFFSET_LSB , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[2].LHR_OFFSET_MSB , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[2].LHR_CONFIG     , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[2].LHR_DATA_LSB   , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[2].LHR_DATA_MID   , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[2].LHR_DATA_MSB   , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[2].LHR_STATUS     , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[2].RID            , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[2].CHIP_ID        , FMSTR_TSA_UINT16)

FMSTR_TSA_RW_VAR(LDC1101_regs[3].RP_SET         , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[3].TC1            , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[3].TC2            , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[3].DIG_CONFIG     , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[3].ALT_CONFIG     , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[3].RP_THRESH_H_LSB, FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[3].RP_THRESH_H_MSB, FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[3].RP_THRESH_L_LSB, FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[3].RP_THRESH_L_MSB, FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[3].INTB_MODE      , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[3].START_CONFIG   , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[3].D_CONF         , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[3].L_THRESH_HI_LSB, FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[3].L_THRESH_HI_MSB, FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[3].L_THRESH_LO_LSB, FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[3].L_THRESH_LO_MSB, FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[3].STATUS         , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[3].RP_DATA_LSB    , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[3].RP_DATA_MSB    , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[3].L_DATA_LSB     , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[3].L_DATA_MSB     , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[3].LHR_RCOUNT_LSB , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[3].LHR_RCOUNT_MSB , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[3].LHR_OFFSET_LSB , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[3].LHR_OFFSET_MSB , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[3].LHR_CONFIG     , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[3].LHR_DATA_LSB   , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[3].LHR_DATA_MID   , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[3].LHR_DATA_MSB   , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[3].LHR_STATUS     , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[3].RID            , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(LDC1101_regs[3].CHIP_ID        , FMSTR_TSA_UINT16)
#endif

FMSTR_TSA_RW_VAR(g_flash_erase_errors           , FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(g_flash_write_errors           , FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(g_flash_crc_errors             , FMSTR_TSA_UINT32)

FMSTR_TSA_RW_VAR(g_int_temp                     , FMSTR_TSA_FLOAT )
FMSTR_TSA_RW_VAR(g_ext_temp                     , FMSTR_TSA_FLOAT )

FMSTR_TSA_RW_VAR(pcbl.host_rx_pack_cnt          , FMSTR_TSA_UINT32)



FMSTR_TSA_TABLE_END()
;

//--------------------------------------------------------------------------------------------------------------
#elif APP_PLATF == ANSMA

extern uint32_t  g_PIT_counter;
extern uint32_t  g_spi_wr_err;
extern uint32_t  g_spi_rd_err;

extern int16_t  angle_int;   
extern float    angle_float; 

FMSTR_TSA_TABLE_BEGIN(tbl_vars)

FMSTR_TSA_RW_VAR(OSStatTaskCPUUsage             , FMSTR_TSA_UINT16)
FMSTR_TSA_RW_VAR(OSStatTaskCPUUsageMax          , FMSTR_TSA_UINT16)

FMSTR_TSA_RW_VAR(g_PIT_counter                  , FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(g_spi_wr_err                   , FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(g_spi_rd_err                   , FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(g_fmstr_rate_src               , FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(g_fmstr_smpls_period           , FMSTR_TSA_FLOAT )

FMSTR_TSA_RW_VAR(g_flash_erase_errors           , FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(g_flash_write_errors           , FMSTR_TSA_UINT32)
FMSTR_TSA_RW_VAR(g_flash_crc_errors             , FMSTR_TSA_UINT32)

FMSTR_TSA_RW_VAR(g_int_temp                     , FMSTR_TSA_FLOAT )
FMSTR_TSA_RW_VAR(g_ext_temp                     , FMSTR_TSA_FLOAT )

FMSTR_TSA_RW_VAR(pcbl.host_rx_pack_cnt          , FMSTR_TSA_UINT32)

FMSTR_TSA_RW_VAR(angle_int                      , FMSTR_TSA_SINT16)
FMSTR_TSA_RW_VAR(angle_float                    , FMSTR_TSA_FLOAT )



FMSTR_TSA_TABLE_END()
;


#else
  #error  Must be selected platform
#endif

